### ISSUE TITLE
Misrepresentative test

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/sinatra-basic-routes-lab#8]
This test:

`describe 'GET /NEW' do 
    it 'sends a 200 status code' do
      get '/new'
      expect(last_response.status).to eq(200)
    end`

Says its looking for '/NEW'
when in actuality it's looking for '/new'

**Comment by drakeltheryuujin** [comment]
Hi @Sillhouette,

I'm not seeing a test that contains this logic. This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
